[build]
  command = "bash ./netlify-build.sh"
  publish = "dist"

# Redirect rule for single-page applications using client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
