[build]
  command = "npm install && npm run build"
  publish = "dist"

# Environment variables
[build.environment]
  # Disable TypeScript's references feature
  TS_NODE_PROJECT = "./tsconfig.json"
  NODE_ENV = "production"

# Redirect rule for single-page applications using client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
